sonar.projectKey=e-commerce-vue
sonar.projectName=e-commerce-vue
sonar.sourceEncoding=UTF-8
sonar.sources=frontend/src,services/auth-service/src,services/product-service/src,services/order-service/src
sonar.tests=frontend/tests,services/auth-service/tests,services/product-service/tests,services/order-service/tests
sonar.test.inclusions=**/*.spec.js,**/*.test.js
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/desktop.ini
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,services/auth-service/coverage/lcov.info,services/product-service/coverage/lcov.info,services/order-service/coverage/lcov.info
